#platform :ios, '10.0'

target 'SwiftCreekSDK' do
  use_frameworks!
  pod 'OCCreekSDK', :path => '../'
  pod 'SnapKit'
  pod 'IQKeyboardManagerSwift'
  pod 'MBProgressHUD'
  pod 'Toast-Swift'
  pod 'ZIPFoundation'
  pod "ESTabBarController-swift"
  pod 'CropViewController'
  pod 'TZImagePickerController'
  
  post_install do |installer|
      installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
              end
          end
      end
  end

end
